### ISSUE TITLE
rhel-7-byol - Error running workflow: step "translate-disk"

### ISSUE THREAD

**Issue by timurshevekhman** [GoogleCloudPlatform/compute-image-tools#161] opened 2017-09-21 16:25 UTC
I have RHEL 7 image created in Oracle VirtualBox that I am trying to import into GCP. I am following the [user guide](https://github.com/GoogleCloudPlatform/compute-image-tools/blob/master/daisy_workflows/import_userguide.md). Step 3 succeeds, but Step 4 is failing:

```
[translate-rhel-7-byol.translate-disk]: 2017/09/21 16:14:47 WaitForInstancesSignal: watching serial port 1, SuccessMatch: "TranslateSuccess:", FailureMatch: "TranslateFailed:".
[translate-rhel-7-byol]: 2017/09/21 16:15:27 Error running workflow: step "translate-disk" run error: step "wait-for-translator" run error: WaitForInstancesSignal: FailureMatch found for instance "inst-translator-translate-rhel-7-byol-translate-disk-7g237"
```

**Comment by zmarano** [comment] 2017-09-21 23:41
Thanks for trying this out! We just made some significant changes to the translation workflows for RHEL and CentOS. Can you try again and let us know how it goes. There may be additional bugs you find that we have not accounted for yet but we will help address those with you.

Release notes:
https://github.com/GoogleCloudPlatform/compute-image-tools/releases/tag/20170921

**Comment by helen-fornazier** [comment] 2017-09-28 21:00
One problem that I faced is that the import script installs the package python-google-compute-engine, and this package requires python-boto as dependency, if your enabled yum repositories don't provide this package then it will fail.

You can verify if this is your case by checking the full log, Daisy creates a folder in your cloud storage bucket with the logs.
If you still have issues when running rhel-7-byol, could you please post the log from the daisy bucket? It should provide more information to check where the issue is.

Thanks

**Comment by zmarano** [comment] 2017-10-23 17:53
Without more info, I'm going to close this issue out. We have made many changes to the translation workflows at this point- please try again and if you run into more problems open a new issue.

**Closed by zmarano** 2017-10-23 17:53 UTC
